version: '3.8'

services:
  smtp4dev:
    image: rnwood/smtp4dev:v3
    ports:
      - "${WEB_PORT}:80"  # Map host port from .env WEB_PORT to container port 80 (web interface)
      - "${SMTP_PORT}:25"  # Map host port from .env SMTP_PORT to container port 25 (SMTP)
    restart: unless-stopped  # Restart container automatically unless manually stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3